//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentFailures
    {
        public int FailureID { get; set; }
        public int EquipmentID { get; set; }
        public int FailureReasonID { get; set; }
        public System.DateTime FailureDate { get; set; }
        public int MasterID { get; set; }
    
        public virtual User User { get; set; }
        public virtual FailureReasons FailureReasons { get; set; }
    }
}
