//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FMaterial()
        {
            this.Specifications = new HashSet<Specifications>();
        }
    
        public int MaterialID { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public int UnitTypeID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Lenght { get; set; }
        public int MaterialTypeID { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string GOST { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
    
        public virtual MaterialsType MaterialsType { get; set; }
        public virtual UnitType UnitType { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Warehouses Warehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specifications> Specifications { get; set; }
    }
}
