//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MComponents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MComponents()
        {
            this.OrderSpecifications = new HashSet<OrderSpecifications>();
        }
    
        public int ComponentID { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public string SpecOfComp { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> UnitTypeID { get; set; }
        public Nullable<int> ComponentTypeID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> WarehouseID { get; set; }
    
        public virtual ComponentsType ComponentsType { get; set; }
        public virtual Warehouses Warehouses { get; set; }
        public virtual UnitType UnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSpecifications> OrderSpecifications { get; set; }
    }
}
