//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FactoryEntities1 : DbContext
    {
        public FactoryEntities1()
            : base("name=FactoryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComponentsType> ComponentsType { get; set; }
        public virtual DbSet<EmployeeOperations> EmployeeOperations { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EquipmentFailures> EquipmentFailures { get; set; }
        public virtual DbSet<Equipments> Equipments { get; set; }
        public virtual DbSet<FailureReasons> FailureReasons { get; set; }
        public virtual DbSet<FMaterial> FMaterial { get; set; }
        public virtual DbSet<MaterialsType> MaterialsType { get; set; }
        public virtual DbSet<MComponents> MComponents { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderSpecifications> OrderSpecifications { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<OrderStatusHistory> OrderStatusHistory { get; set; }
        public virtual DbSet<QualityChecks> QualityChecks { get; set; }
        public virtual DbSet<QualityParameters> QualityParameters { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UnitType> UnitType { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserImage> UserImage { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
    }
}
