//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityChecks
    {
        public int CheckID { get; set; }
        public int OrderID { get; set; }
        public int ParameterID { get; set; }
        public bool IsCheck { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual QualityParameters QualityParameters { get; set; }
    }
}
